# Generated by Django 4.2.10 on 2024-02-23 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HelloMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_body', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('carrier', models.CharField(choices=[('DGJ', 'Django'), ('DRF', 'Django Rest Framework')], default='DGJ', max_length=3)),
            ],
        ),
    ]
