FROM python:3.10-slim
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN pip install --upgrade pip

ENV APP_HOME /core
WORKDIR ${APP_HOME}

COPY ./app/requirements ./app/requirements
RUN pip install --no-cache-dir -r ./app/requirements/local.txt

# Skip this since volume is mounted in the compose file
# COPY . .

# Run gunicorn inside the /app directory
WORKDIR ${APP_HOME}/app
CMD ["gunicorn", "-c", "./config/gunicorn.local.py", "app.wsgi:application", "--reload"]
